/**
 * This code was generated by Builder.io.
 */
import React from 'react'

import { MuiFileInput } from 'mui-file-input'

import styled from 'styled-components'

const ImagePreview: React.FC = () => {
  const [value, setValue] = React.useState<null | File[]>(null)

  const handleChange = (newValue: any) => {
    console.log('newValue', newValue)
    setValue(newValue)
  }

  return (
    <StyledPreview>
      <StyledLabel htmlFor={'images'}>Choose images</StyledLabel>
      <MuiFileInput
        id={'images'}
        name={'images'}
        multiple
        value={value || undefined}
        onChange={handleChange}
      />
      <GridContainer>
        {value &&
          value?.map(el => {
            const previewSrc = URL.createObjectURL(el)
            return (
              <img
                key={el.name}
                width={'100%'}
                src={previewSrc || ''}
                alt="preview"
              />
            )
          })}
      </GridContainer>
    </StyledPreview>
  )
}

const StyledPreview = styled.div`
  margin-top: 17px;
  display: flex;
  flex-direction: column;
  gap: 8px;
`

const GridContainer = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
`

const StyledLabel = styled.label`
  color: #141c24;
  font-weight: 500;
  font-size: 16px;
  margin-bottom: 8px;
`

export default ImagePreview
