/**
 * This code was generated by Builder.io.
 */
import React, { MutableRefObject, useEffect, useRef } from 'react'

import styled from 'styled-components'

import FormField from './FormField'
import ImagePreview from './ImagePreview'
import SubmitButton from './SubmitButton'
import { useTranslation } from 'react-i18next'
import axios from 'axios'

interface ReportIssueFormProps {
  // onSubmit: (formData: FormData) => void
}

const validateForm = (formFields: (string | File)[][]) => {
  let isValid = true
  formFields.forEach(el => {
    if (el[0] === 'feedback') {
      if (el[1] !== 'string' || el[1].length < 10) {
        isValid = false
      }
    }
  })
  return isValid
}

const ReportIssueForm: React.FC<ReportIssueFormProps> = () => {
  const { t, i18n } = useTranslation()
  const ref: MutableRefObject<HTMLFormElement | null> = useRef(null)
  const childRef = useRef()

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const formData = new FormData(event.currentTarget)
    ref.current?.reset()
    // @ts-ignore
    childRef.current?.reset()

    console.log('formData', Array.from(formData.entries()))

    if (validateForm(Array.from(formData.entries()))) {
      console.log('SENDING')
      // TODO change to actual back-end url
      axios({
        method: 'post',
        url: 'http://localhost:8000/api/Applications/validate',
        data: formData,
        headers: { 'Content-Type': 'multipart/form-data' }
      })
    }
  }

  return (
    <StyledForm ref={ref} onSubmit={handleSubmit}>
      <header className="form-header">
        <h1>{t('title')}</h1>
        <button className="close-button" aria-label="Close form">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ec010c5c1de94aa5c29420619e3bd3926a552243202d57c32b533cec1c45d31?placeholderIfAbsent=true&apiKey=a552dda26a534b4199e019b86be48e11"
            alt="Close"
          />
        </button>
      </header>
      <main>
        <FormField label={t('labels.name')} id="name" type="text" />
        <FormField label={t('labels.phone')} id="phone" type="tel" />
        <FormField label={t('labels.feedback')} id="feedback" type="textarea" />
        <ImagePreview ref={childRef} />
        <SubmitButton />
      </main>
    </StyledForm>
  )
}

const StyledForm = styled.form`
  background-color: #f7fafa;
  max-width: 480px;
  width: 100%;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  justify-content: space-between;

  .form-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 16px 16px 8px;

    h1 {
      flex: 1;
      text-align: center;
      font: 700 18px/1 'Public Sans', sans-serif;
      color: #141c24;
    }
  }

  main {
    flex: 1;
    display: flex;
    flex-direction: column;
    padding: 0 16px 16px;
  }
`

export default ReportIssueForm
