/**
 * This code was generated by Builder.io.
 */
import React from 'react'

import styled from 'styled-components'

import FormField from './FormField'
import ImagePreview from './ImagePreview'
import SubmitButton from './SubmitButton'

interface ReportIssueFormProps {
  onSubmit: (formData: FormData) => void
}

const ReportIssueForm: React.FC<ReportIssueFormProps> = ({ onSubmit }) => {
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const formData = new FormData(event.currentTarget)
    onSubmit(formData)
  }

  return (
    <StyledForm onSubmit={handleSubmit}>
      <header className="form-header">
        <h1>Report an issue</h1>
        <button className="close-button" aria-label="Close form">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ec010c5c1de94aa5c29420619e3bd3926a552243202d57c32b533cec1c45d31?placeholderIfAbsent=true&apiKey=a552dda26a534b4199e019b86be48e11"
            alt="Close"
          />
        </button>
      </header>
      <main>
        <FormField
          label="First and last name"
          id="name"
          type="text"
          placeholder="Name"
        />
        <FormField
          label="Your phone number"
          id="phone"
          type="tel"
          placeholder="Phone number"
        />
        <FormField label="Feedback" id="feedback" type="textarea" />
        <ImagePreview />
        <SubmitButton />
      </main>
    </StyledForm>
  )
}

const StyledForm = styled.form`
  background-color: #f7fafa;
  max-width: 480px;
  width: 100%;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  min-height: 844px;
  justify-content: space-between;

  .form-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 16px 16px 8px;

    h1 {
      flex: 1;
      text-align: center;
      font: 700 18px/1 'Public Sans', sans-serif;
      color: #141c24;
    }

    .close-button {
      background: none;
      border: none;
      padding: 0;
      width: 24px;
      height: 24px;
      cursor: pointer;

      img {
        width: 100%;
        height: 100%;
      }
    }
  }

  main {
    flex: 1;
    display: flex;
    flex-direction: column;
    padding: 0 16px 16px;
  }
`

export default ReportIssueForm
